# Generated by Django 3.1.3 on 2020-11-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proom',
            name='service',
            field=models.CharField(default='s', max_length=70),
        ),
    ]
