# Generated by Django 3.1.3 on 2020-11-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='guest',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='room',
            field=models.IntegerField(),
        ),
    ]
