# Generated by Django 3.1.3 on 2020-11-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201127_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='Phone',
            field=models.IntegerField(default=''),
        ),
    ]
