# Generated by Django 3.1.3 on 2020-11-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reserve_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='Phone',
            field=models.IntegerField(),
        ),
    ]
