# Generated by Django 3.1.3 on 2020-11-28 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201128_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='Phone',
        ),
    ]
