# Generated by Django 3.1.3 on 2020-11-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simg', models.ImageField(upload_to='images')),
                ('ctitle', models.CharField(max_length=70)),
                ('cpara', models.TextField()),
            ],
        ),
    ]
