# Generated by Django 3.1.3 on 2020-11-22 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='slide',
            new_name='slid',
        ),
    ]
