# Generated by Django 3.1.3 on 2020-11-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_auto_20201122_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlogo', models.ImageField(upload_to='media')),
                ('mname', models.CharField(max_length=70)),
                ('mprice', models.IntegerField()),
            ],
        ),
    ]
