# Generated by Django 3.1.3 on 2020-11-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=70)),
                ('phone_number', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('number_Of_Members', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=50)),
            ],
        ),
    ]
