# Generated by Django 3.1.3 on 2020-11-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='table',
            name='number_Of_Members',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=50),
        ),
    ]
