# Generated by Django 3.1.3 on 2020-11-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_auto_20201123_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
