# Generated by Django 3.1.3 on 2020-11-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_auto_20201123_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='time',
            field=models.TimeField(),
        ),
    ]
