# Generated by Django 3.1.3 on 2020-11-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_auto_20201123_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='foodoffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oimg', models.ImageField(upload_to='media')),
                ('oname', models.CharField(max_length=90)),
                ('oprice', models.IntegerField()),
                ('ooffer', models.BooleanField()),
            ],
        ),
    ]
