# Generated by Django 3.1.3 on 2020-11-23 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_foodoffer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='foodoffer',
        ),
    ]
