# Generated by Django 3.1.3 on 2020-11-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_delete_foodoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='himg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media')),
            ],
        ),
    ]
