# Generated by Django 3.1.3 on 2020-11-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='theimg',
            field=models.ImageField(default='img', upload_to='images/'),
        ),
    ]
