# Generated by Django 3.1.3 on 2020-11-08 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_theimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='theimg',
        ),
    ]
