# Generated by Django 3.1.3 on 2020-12-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_market'),
    ]

    operations = [
        migrations.CreateModel(
            name='stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_price', models.UUIDField()),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
